CompassMQTT/Models/CompassModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompassMQTT.Models
{
	public class CompassModel
	{
		public Feed[] feeds { get; set; }
	}

	public class Feed
	{
		public DateTime created_at { get; set; }
		public string field1 { get; set; }
		public string field2 { get; set; }
		public string field3 { get; set; }
	}

}

CompassMQTT/Models/CompassViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompassMQTT.Models
{
	public class CompassViewModel
	{
		public DateTime created_at { get; set; }
		public double? X { get; set; }
		public double? Y { get; set; }
		public double? Z { get; set; }
	}
}

CompassMQTT/Models/ErrorViewModel.cs
using System;

namespace CompassMQTT.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

CompassMQTT/Controllers/CompassController.cs
using CompassMQTT.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Net.Http;
using CompassMQTT.Models;

namespace CompassMQTT.Controllers
{
	public class CompassController : Controller
	{
		private readonly ICharts _charts;
		private string url = "https://api.thingspeak.com/channels/1236818/feeds.json?api_key=W4GDVI0MFIYV9S0A";

		public CompassController(ICharts charts)
		{
			_charts = charts;
		}

		public async Task<ActionResult> IndexAsync()
		{
			HttpClient client = new HttpClient();
			string jsonFile = await client.GetStringAsync(url);
			CompassModel compassData = JsonConvert.DeserializeObject<CompassModel>(jsonFile);

			List<CompassViewModel> compassList = new List<CompassViewModel>();
			foreach (var item in compassData.feeds)
			{
				compassList.Add(new CompassViewModel {
					created_at = item.created_at,
					X = double.Parse(item.field1),
					Y = double.Parse(item.field2),
					Z = double.Parse(item.field3)
				});
			}
			ViewData[$"CompassDataX"] = _charts.getLineChart(compassList.Select(x => x.X).ToList(), compassList.Select(x => x.created_at.ToString()).ToList(), "X");
			ViewData[$"CompassDataY"] = _charts.getLineChart(compassList.Select(x => x.Y).ToList(), compassList.Select(x => x.created_at.ToString()).ToList(), "Y");
			ViewData[$"CompassDataZ"] = _charts.getLineChart(compassList.Select(x => x.Z).ToList(), compassList.Select(x => x.created_at.ToString()).ToList(), "Z");
			return View();
		}
	}
}

CompassMQTT/Controllers/HomeController.cs
using CompassMQTT.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CompassMQTT.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

CompassMQTT/Views/Compass/Index.cshtml
@{
	ViewData["Title"] = "CompassCharts";
}

<div class="container fluid">
	<div class="row">
		<div class="offset-1 col-10 text-center">
			<br />
			<h2> <i class="fas fa-tint mb-3 mr-3"></i>Compass X Chart</h2>
			<hr />
			<br />
		</div>
		<div class="offset-1 col-10 algin-left">

			Compass X Chart<canvas id="CompassDataX"></canvas>

		</div>
	</div>
	<div class="row">
		<div class="offset-1 col-10 text-center">
			<br />
			<h2> <i class="fas fa-tint mb-3 mr-3"></i>Compass Y Chart</h2>
			<hr />
			<br />
		</div>
		<div class="offset-1 col-10 algin-left">

			Compass Y Chart<canvas id="CompassDataY"></canvas>

		</div>
	</div>
	<div class="row">
		<div class="offset-1 col-10 text-center">
			<br />
			<h2> <i class="fas fa-tint mb-3 mr-3"></i>Compass Z Chart</h2>
			<hr />
			<br />
		</div>
		<div class="offset-1 col-10 algin-left">

			Compass Z Chart<canvas id="CompassDataZ"></canvas>

		</div>
	</div>
</div>

@{ChartJSCore.Models.Chart CompassDataX = (ChartJSCore.Models.Chart)ViewData["CompassDataX"]; }
@{ChartJSCore.Models.Chart CompassDataY = (ChartJSCore.Models.Chart)ViewData["CompassDataY"]; }
@{ChartJSCore.Models.Chart CompassDataZ = (ChartJSCore.Models.Chart)ViewData["CompassDataZ"]; }
@section Scripts {
	<script>
        @Html.Raw(CompassDataX.CreateChartCode("CompassDataX"));
		@Html.Raw(CompassDataY.CreateChartCode("CompassDataY"));
		@Html.Raw(CompassDataZ.CreateChartCode("CompassDataZ"));
	</script>
}

CompassMQTT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CompassMQTT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CompassMQTT</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/chart.js-2.8.0/dist/Chart.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Compass" asp-action="Index">CompassMQTT</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2021 - CompassMQTT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/chart.js-2.8.0/dist/Chart.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>